require "active_support/dependencies"

module Shortener

  autoload :ActiveRecordExtension, "shortener/active_record_extension"
  autoload :ShortenUrlInterceptor, "shortener/shorten_url_interceptor"

  CHARSETS = {
    alphanum: ('a'..'z').to_a + (0..9).to_a,
    alphanumcase: ('a'..'z').to_a + ('A'..'Z').to_a + (0..9).to_a
  }

  CRAWLERS_USER_AGENT_LIST = [
    "( Robots.txt Validator http://www.searchengineworld.com/cgi-bin/robotcheck.cgi )",
    "123spider-Bot (Version: 1.02, powered by www.123spider.de",
    "2Bone_LinkChecker/1.0 libwww-perl/5.64",
    "A1 Keyword Research/1.0.2 (+http://www.micro-sys.dk/products/keyword-research/) miggibot/2007.03.27",
    "Adaxas Spider (http://www.adaxas.net/)",
    "AideRSS/1.0 (aiderss.com)",
    "amzn_assoc",
    "aranhabot",
    "Argus/1.1 (Nutch; http://www.simpy.com/bot.html; feedback at simpy dot com)",
    "autohttp",
    "BanBots/1.2 (spider@banbots.com)",
    "BeebwareDirectory/v0.01",
    "Big Brother (http://pauillac.inria.fr/~fpottier/)",
    "Big Fish v1.0",
    "BigBrother/1.6e",
    "Bilbo/2.3b-UNIX",
    "billbot wjj@cs.cmu.edu",
    "BlogMap (http://www.feedmap.net)",
    "BMLAUNCHER",
    "Bobby/4.0.x RPT-HTTPClient/0.3-3E",
    "Bookdog/x.x",
    "Bookmark Buddy bookmark checker (http://www.bookmarkbuddy.net/)",
    "Bookmark Renewal Check Agent [http://www.bookmark.ne.jp/]",
    "Bookmark Renewal Check Agent [http://www.bookmark.ne.jp/] (Version 2.0beta)",
    "BookmarkBase(2/;http://bookmarkbase.com)",
    "Bulkfeeds/r1752 (http://bulkfeeds.net/)",
    "BunnySlippers",
    "CentiverseBot",
    "CentiverseBot - investigator",
    "CentiverseBot/3.0 (http://www.centiverse-project.net)",
    "cg-eye interactive",
    "Chat Catcher/1.0",
    "Checkbot/1.xx LWP/5.xx",
    "CheckLinks/1.x.x",
    "CheckWeb",
    "Chitika ContentHit 1.0",
    "Cityreview Robot (+http://www.cityreview.org/crawler/)",
    "CJ Spider/",
    "COAST WebMaster Pro/4.x.x.xx (Windows NT)",
    "Cocoal.icio.us/1.0 (v36) (Mac OS X; http://www.scifihifi.com/cocoalicious)",
    "ColdFusion (BookmarkTracker.com)",
    "complex_network_group/Nutch-0.9-dev (discovering the structure of the world-wide-web; http://cantor.ee.ucla.edu/~networks/crawl; nimakhaj@gmail.com)",
    "CoteoNutchCrawler/Nutch-0.9 (info [at] coteo [dot] com)",
    "CSE HTML Validator Professional (http://www.htmlvalidator.com/)",
    "Custo x.x (www.netwu.com)",
    "CyberSpyder Link Test/2.1.12 (admin@mspennyworth.com)",
    "DeadLinkCheck/0.4.0 libwww-perl/5.xx",
    "Deep Link Calculator v1.0",
    "disastrous/1.0.5 (running with Python 2.5.1; http://www.bortzmeyer.org/disastrous.html; archangel77@del.icio.us)",
    "DNSRight.com WebBot Link Ckeck Tool. Report abuse to: dnsr@dnsright.com",
    "Drupal (+http://drupal.org/)",
    "EldoS TimelyWeb/3.x",
    "FaEdit/2.0.x",
    "FARK.com link verifier",
    "FAST Enterprise Crawler 6 used by WWU (wardi@uni-muenster.de)",
    "FavOrg",
    "Favorites Checking (http://campulka.net)",
    "Favorites Sweeper v.2.03",
    "Feedfetcher-Google-iGoogleGadgets; (+http://www.google.com/feedfetcher.html)",
    "FeedForAll rss2html.php v2",
    "flyindex.net 1.0/http://www.flyindex.net",
    "FollowSite Bot ( http://www.followsite.com/bot.html )",
    "FollowSite.com ( http://www.followsite.com/b.html )",
    "free-downloads.net download-link validator /0.1",
    "Frelicbot/1.0 +http://www.frelic.com/",
    "unknownght.com Web Server IIS vs Apache Survey. See Results at www.DNSRight.com",
    "ActiveBookmark 1.x",
    "FLATARTS_FAVICO",
    "!Susie (http://www.sync2it.com/susie)",
    "Alligator 1.31 (www.nearsoftware.com)",
    "Azureus 2.x.x.x",
    "BackStreet Browser 3.x",
    "BlackWidow",
    "BTWebClient/180B(9704)",
    "BW-C-2.0",
    "Charon/1.x (Amiga)",
    "curl/7.10.x (i386-redhat-linux-gnu) libcurl/7.10.x OpenSSL/0.9.7a ipv6 zlib/1.1.4",
    "curl/7.7.x (i386--freebsd4.3) libcurl 7.7.x (SSL 0.9.6) (ipv6 enabled)",
    "curl/7.8 (i686-pc-linux-gnu) libcurl 7.8 (OpenSSL 0.9.6)",
    "curl/7.9.x (win32) libcurl 7.9.x",
    "DA 3.5 (www.lidan.com)",
    "DA 4.0",
    "DA 4.0 (www.downloadaccelerator.com)",
    "DA 5.0",
    "DA 7.0",
    "DAP x.x",
    "DC-Sakura/x.xx",
    "DDD",
    "del.icio.us-thumbnails/1.0 Mozilla/5.0 (compatible; Konqueror/3.4; FreeBSD) KHTML/3.4.2 (like Gecko)",
    "Der große BilderSauger 2.00u",
    "DISCo Pump x.x",
    "dlman",
    "Download Demon/3.x.x.x",
    "Download Druid 2.x",
    "Download Express 1.0",
    "Download Master",
    "Download Ninja 3.0",
    "Download Wonder",
    "Download.exe(1.1) (+http://www.sql-und-xml.de/freeware-tools/)",
    "DownloadDirect.1.0",
    "Extreme Picture Finder",
    "FavIconizer",
    "FDM 1.x",
    "FDM 2.x",
    "Feed::Find/0.0x",
    "fetch libfetch/2.0",
    "FileHound x.x",
    "FlashGet",
    "FreshDownload/x.xx",
    "(Privoxy/1.0)",
    "Ad Muncher v4.xx.x",
    "Ad Muncher v4x Build xxxxx",
    "Anonymized by ProxyOS: http://www.megaproxy.com",
    "CE-Preload",
    "CJB.NET Proxy",
    "DeleGate/9.0.5-fix1",
    "DoCoMo/1.0/P502i/c10 (Google CHTML Proxy/1.0)",
    "DoCoMo/2.0 SH901iS(c100;TB;W24H12),gzip(gfe) (via translate.google.com)",
    "Dual Proxy",
    "FairAd Client",
    "FANGCrawl/0.01",
    "Finjan-prefetch",
    "ColdFusion",
    "CoralWebPrx/0.1.1x (See http://coralcdn.org/)",
    "BravoBrian bstop.bravobrian.it",
    "BrightCrawler (http://www.brightcloud.com/brightcrawler.asp)",
    "BStop.BravoBrian.it Agent Detector",
    "EmeraldShield.com WebBot",
    "EmeraldShield.com WebBot (http://www.emeraldshield.com/webbot.aspx)",
    "<a href='http://www.unchaos.com/'> UnChaos </a> From Chaos To Order Hybrid Web Search Engine.(vadim_gonchar@unchaos.com)",
    "<a href='http://www.unchaos.com/'> UnChaos Bot Hybrid Web Search Engine. </a> (vadim_gonchar@unchaos.com)",
    "<b> UnChaosBot From Chaos To Order UnChaos Hybrid Web Search Engine at www.unchaos.com </b> (info@unchaos.com)",
    "<http://www.sygol.com/> http://www.sygol.com",
    "*/Nutch-0.9-dev",
    "#ERROR!",
    "-DIE-KRAEHE- META-SEARCH-ENGINE/1.1 http://www.die-kraehe.de",
    "192.comAgent",
    "4anything.com LinkChecker v2.0",
    ":robot/1.0 (linux) ( admin e-mail: undefined http://www.neofonie.de/loesungen/search/robot.html )",
    "A-Online Search",
    "A1 Sitemap Generator/1.0 (+http://www.micro-sys.dk/products/sitemap-generator/) miggibot/2006.01.24",
    "aardvark-crawler",
    "AbachoBOT",
    "AbachoBOT (Mozilla compatible)",
    "ABCdatos BotLink/5.xx.xxx#BBL",
    "Aberja Checkomat",
    "abot/0.1 (abot; http://www.abot.com; abot@abot.com)",
    "About/0.1libwww-perl/5.47",
    "Accelatech RSSCrawler/0.4",
    "accoona",
    "Accoona-AI-Agent/1.1.1 (crawler at accoona dot com)",
    "Accoona-AI-Agent/1.1.2 (aicrawler at accoonabot dot com)",
    "Ack (http://www.ackerm.com/)",
    "AcoiRobot",
    "Acoon Robot v1.50.001",
    "Acoon Robot v1.52 (http://www.acoon.de)",
    "Acoon-Robot 4.0.x.[xx] (http://www.acoon.de)",
    "Acoon-Robot v3.xx (http://www.acoon.de and http://www.acoon.com)",
    "Acorn/Nutch-0.9 (Non-Profit Search Engine; acorn.isara.org; acorn at isara dot org)",
    "AESOP_com_SpiderMan",
    "agadine/1.x.x (+http://www.agada.de)",
    "Agent-SharewarePlazaFileCheckBot/2.0+(+http://www.SharewarePlaza.com)",
    "AgentName/0.1 libwww-perl/5.48",
    "AIBOT/2.1 By +(www.21seek.com A Real artificial intelligence search engine China)",
    "aipbot/1.0 (aipbot; http://www.aipbot.com; aipbot@aipbot.com)",
    "aipbot/2-beta (aipbot dev; http://aipbot.com; aipbot@aipbot.com)",
    "Aladin/3.324",
    "Aleksika Spider/1.0 (+http://www.aleksika.com/)",
    "AlkalineBOT/1.3",
    "AlkalineBOT/1.4 (1.4.0326.0 RTM)",
    "Allesklar/0.1 libwww-perl/5.46",
    "Allrati/1.1 (+)",
    "AltaVista Intranet V2.0 AVS EVAL search@freeit.com",
    "AltaVista Intranet V2.0 Compaq Altavista Eval sveand@altavista.net",
    "AltaVista Intranet V2.0 evreka.com crawler@evreka.com",
    "AltaVista V2.0B crawler@evreka.com",
    "AmfibiBOT",
    "Amfibibot/0.06 (Amfibi Web Search; http://www.amfibi.com; agent@amfibi.com)",
    "Amfibibot/0.07 (Amfibi Robot; http://www.amfibi.com; agent@amfibi.com)",
    "amibot",
    "AnnoMille spider 0.1 alpha - http://www.annomille.it",
    "AnswerBus (http://www.answerbus.com/)",
    "antibot-V1.1.5/i586-linux-2.2",
    "AnzwersCrawl/2.0 (anzwerscrawl@anzwers.com.au;Engine)",
    "Apexoo Spider 1.x",
    "Aport",
    "appie 1.1 (www.walhello.com)",
    "ArabyBot (compatible; Mozilla/5.0; GoogleBot; FAST Crawler 6.4; http://www.araby.com;)",
    "ArachBot",
    "Arachnoidea (arachnoidea@euroseek.com)",
    "ArchitextSpider",
    "archive.org_bot",
    "Arikus_Spider",
    "Arquivo-web-crawler (compatible; heritrix/1.12.1 +http://arquivo-web.fccn.pt)",
    "ASAHA Search Engine Turkey V.001 (http://www.asaha.com/)",
    "Asahina-Antenna/1.x",
    "Asahina-Antenna/1.x (libhina.pl/x.x ; libtime.pl/x.x)",
    "ask.24x.info",
    "AskAboutOil/0.06-rcp (Nutch; http://www.nutch.org/docs/en/bot.html; nutch-agent@askaboutoil.com)",
    "asked/Nutch-0.8 (web crawler; http://asked.jp; epicurus at gmail dot com)",
    "ASPSeek/1.2.5",
    "ASPseek/1.2.9d",
    "ASPSeek/1.2.x",
    "ASPSeek/1.2.xa",
    "ASPseek/1.2.xx",
    "ASPSeek/1.2.xxpre",
    "ASSORT/0.10",
    "asterias/2.0",
    "AtlocalBot/1.1 +(http://www.atlocal.com/local-web-site-owner.html)",
    "Atomz/1.0",
    "Attentio/Nutch-0.9-dev (Attentio's beta blog crawler; www.attentio.com; info@attentio.com)",
    "augurfind",
    "augurnfind V-1.x",
    "autowebdir 1.1 (www.autowebdir.com)",
    "AV Fetch 1.0",
    "AVSearch-1.0(peter.turney@nrc.ca)",
    "AVSearch-3.0(AltaVista/AVC)",
    "axadine/ (Axadine Crawler; http://www.axada.de/; )",
    "AxmoRobot - Crawling your site for better indexing on www.axmo.com search engine.",
    "BabalooSpider/1.3 (BabalooSpider; http://www.babaloo.si; spider@babaloo.si)",
    "BaboomBot/1.x.x (+http://www.baboom.us)",
    "BaiduImagespider+(+http://www.baidu.jp/search/s308.html)",
    "BaiDuSpider",
    "Baiduspider+(+http://help.baidu.jp/system/05.html)",
    "Baiduspider+(+http://www.baidu.com/search/spider.htm)",
    "Baiduspider+(+http://www.baidu.com/search/spider_jp.html)",
    "Balihoo/Nutch-1.0-dev (Crawler for Balihoo.com search engine - obeys robots.txt and robots meta tags ; http://balihoo.com/index.aspx; robot at balihoo dot com)",
    "BarraHomeCrawler (albertof@barrahome.org)",
    "bdcindexer_2.6.2 (research@bdc)",
    "BDFetch",
    "BDNcentral Crawler v2.3 [en] (http://www.bdncentral.com/robot.html) (X11; I; Linux 2.0.44 i686)",
    "beautybot/1.0 (+http://www.uchoose.de/crawler/beautybot/)",
    "BebopBot/2.5.1 ( crawler http://www.apassion4jazz.net/bebopbot.html )",
    "BigCliqueBOT/1.03-dev (bigclicbot; http://www.bigclique.com; bot@bigclique.com)",
    "BIGLOTRON (Beta 2;GNU/Linux)",
    "Bigsearch.ca/Nutch-x.x-dev (Bigsearch.ca Internet Spider; http://www.bigsearch.ca/; info@enhancededge.com)",
    "BilgiBetaBot/0.8-dev (bilgi.com (Beta) ; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
    "BilgiBot/1.0(beta) (http://www.bilgi.com/; bilgi at bilgi dot com)",
    "Bitacle bot/1.1",
    "Bitacle Robot (V:1.0;) (http://www.bitacle.com)",
    "BlackWidow",
    "Blaiz-Bee/1.0 (+http://www.blaiz.net)",
    "Blaiz-Bee/2.00.8222 (BE Internet Search Engine http://www.rawgrunt.com)",
    "Blaiz-Bee/2.00.xxxx (+http://www.blaiz.net)",
    "BlitzBOT@tricus.net",
    "BlitzBOT@tricus.net (Mozilla compatible)",
    "BlogBot/1.x",
    "Bloglines Title Fetch/1.0 (http://www.bloglines.com)",
    "Bloglines-Images/0.1 (http://www.bloglines.com)",
    "Bloglines/3.1 (http://www.bloglines.com)",
    "Blogpulse (info@blogpulse.com)",
    "BlogPulseLive (support@blogpulse.com)",
    "BlogSearch/1.x +http://www.icerocket.com/",
    "blogsearchbot-pumpkin-3",
    "BlogsNowBot, V 2.01 (+http://www.blogsnow.com/)",
    "BlogVibeBot-v1.1 (spider@blogvibe.nl)",
    "blogWatcher_Spider/0.1 (http://www.lr.pi.titech.ac.jp/blogWatcher/)",
    "BlogzIce/1.0 (+http://icerocket.com; rhodes@icerocket.com)",
    "BlogzIce/1.0 +http://www.icerocket.com/",
    "BloobyBot",
    "Bloodhound/Nutch-0.9 (Testing Crawler for Research - obeys robots.txt and robots meta tags ; http://balihoo.com/index.aspx; robot at balihoo dot com)",
    "boitho.com-dc/0.xx (http://www.boitho.com/dcbot.html)",
    "boitho.com-robot/1.x",
    "boitho.com-robot/1.x (http://www.boitho.com/bot.html)",
    "BPImageWalker/2.0 (www.bdbrandprotect.com)",
    "BravoBrian SpiderEngine MarcoPolo",
    "BruinBot (+http://webarchive.cs.ucla.edu/bruinbot.html)",
    "BSDSeek/1.0",
    "BTbot/0.x (+http://www.btbot.com/btbot.html)",
    "BuildCMS crawler (http://www.buildcms.com/crawler)",
    "BullsEye",
    "bumblebee@relevare.com",
    "BurstFindCrawler/1.1 (crawler.burstfind.com; http://crawler.burstfind.com; crawler@burstfind.com)",
    "Buscaplus Robi/1.0 (http://www.buscaplus.com/robi/)",
    "Cabot/Nutch-0.9 (Amfibi's web-crawling robot; http://www.amfibi.com/cabot/; agent@amfibi.com)",
    "Cabot/Nutch-1.0-dev (Amfibi's web-crawling robot; http://www.amfibi.com/cabot/; agent@amfibi.com)",
    "carleson/1.0",
    "Carnegie_Mellon_University_Research_WebBOT-->PLEASE READ-->http://www.andrew.cmu.edu/~brgordon/webbot/index.html http://www.andrew.cmu.edu/~brgordon/webbot/index.html",
    "Carnegie_Mellon_University_WebCrawler http://www.andrew.cmu.edu/~brgordon/webbot/index.html",
    "Catall Spider",
    "CazoodleBot/CazoodleBot-0.1 (CazoodleBot Crawler; http://www.cazoodle.com/cazoodlebot; cazoodlebot@cazoodle.com)",
    "CCBot/1.0 (+http://www.commoncrawl.org/bot.html)",
    "ccubee/x.x",
    "Ceramic Tile Installation Guide (http://www.floorstransformed.com)",
    "cfetch/1.0",
    "ChristCRAWLER 2.0",
    "CipinetBot (http://www.cipinet.com/bot.html)",
    "ClariaBot/1.0",
    "Claymont.com",
    "CloakDetect/0.9 (+http://fulltext.seznam.cz/)",
    "Clushbot/2.x (+http://www.clush.com/bot.html)",
    "Clushbot/3.x-BinaryFury (+http://www.clush.com/bot.html)",
    "Clushbot/3.xx-Ajax (+http://www.clush.com/bot.html)",
    "Clushbot/3.xx-Hector (+http://www.clush.com/bot.html)",
    "Clushbot/3.xx-Peleus (+http://www.clush.com/bot.html)",
    "Cogentbot/1.X (+http://www.cogentsoftwaresolutions.com/bot.html)",
    "combine/0.0",
    "Combine/2.0 http://combine.it.lth.se/",
    "Combine/3 http://combine.it.lth.se/",
    "Combine/x.0",
    "cometrics-bot, http://www.cometrics.de",
    "Computer_and_Automation_Research_Institute_Crawler crawler@ilab.sztaki.hu",
    "Comrite/0.7.1 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
    "Convera Internet Spider V6.x",
    "ConveraCrawler/0.2",
    "ConveraCrawler/0.9d (+http://www.authoritativeweb.com/crawl)",
    "ConveraMultiMediaCrawler/0.1 (+http://www.authoritativeweb.com/crawl)",
    "CoolBot",
    "cosmos/0.8_(robot@xyleme.com)",
    "cosmos/0.9_(robot@xyleme.com)",
    "CougarSearch/0.x (+http://www.cougarsearch.com/faq.shtml)",
    "Covac TexAs Arachbot",
    "Cowbot-0.1 (NHN Corp. / +82-2-3011-1954 / nhnbot@naver.com)",
    "Cowbot-0.1.x (NHN Corp. / +82-2-3011-1954 / nhnbot@naver.com)",
    "CrawlConvera0.1 (CrawlConvera@yahoo.com)",
    "Crawler (cometsearch@cometsystems.com)",
    "Crawler admin@crawler.de",
    "Crawler V 0.2.x admin@crawler.de",
    "crawler@alexa.com",
    "CrawlerBoy Pinpoint.com",
    "Crawllybot/0.1 (Crawllybot; +http://www.crawlly.com; crawler@crawlly.com)",
    "CreativeCommons/0.06-dev (Nutch; http://www.nutch.org/docs/en/bot.html; nutch-agent@lists.sourceforge.net)",
    "CrocCrawler vx.3 [en] (http://www.croccrawler.com) (X11; I; Linux 2.0.44 i686)",
    "csci_b659/0.13",
    "Cuasarbot/0.9b http://www.cuasar.com/spider_beta/",
    "CurryGuide SiteScan 1.1",
    "Custom Spider www.bisnisseek.com /1.0",
    "CyberPatrol SiteCat Webbot (http://www.cyberpatrol.com/cyberpatrolcrawler.asp)",
    "CydralSpider/1.x (Cydral Web Image Search; http://www.cydral.com)",
    "CydralSpider/3.0 (Cydral Image Search; http://www.cydral.com)",
    "DataFountains/DMOZ Downloader",
    "DataFountains/Dmoz Downloader (http://ivia.ucr.edu/useragents.shtml)",
    "DataFountains/DMOZ Feature Vector Corpus Creator (http://ivia.ucr.edu/useragents.shtml)",
    "DataparkSearch/4.47 (+http://dataparksearch.org/bot)",
    "DataparkSearch/4.xx (http://www.dataparksearch.org/)",
    "DataSpear/1.0 (Spider; http://www.dataspear.com/spider.html; spider@dataspear.com)",
    "DataSpearSpiderBot/0.2 (DataSpear Spider Bot; http://dssb.dataspear.com/bot.html; dssb@dataspear.com)",
    "DatenBot( http://www.sicher-durchs-netz.de/bot.html)",
    "DaviesBot/1.7 (www.wholeweb.net)",
    "daypopbot/0.x",
    "dbDig(http://www.prairielandconsulting.com)",
    "dCSbot/1.1",
    "de.searchengine.comBot 1.2 (http://de.searchengine.com/spider)",
    "deepak-USC/ISI",
    "DeepIndex",
    "DeepIndex ( http://www.zetbot.com )",
    "DeepIndex (www.en.deepindex.com)",
    "DeepIndexer.ca",
    "Denmex websearch (http://search.denmex.com)",
    "dev-spider2.searchpsider.com/1.3b",
    "DiaGem/1.1 (http://www.skyrocket.gr.jp/diagem.html)",
    "Diamond/x.0",
    "DiamondBot",
    "Digger/1.0 JDK/1.3.0rc3",
    "DigOut4U",
    "DIIbot/1.2",
    "disco/Nutch-0.9 (experimental crawler; www.discoveryengine.com; disco-crawl@discoveryengine.com)",
    "disco/Nutch-1.0-dev (experimental crawler; www.discoveryengine.com; disco-crawl@discoveryengine.com)",
    "DittoSpyder",
    "dloader(NaverRobot)/1.0",
    "DoCoMo/1.0/Nxxxi/c10",
    "DoCoMo/1.0/Nxxxi/c10/TB",
    "DoCoMo/2.0 P900iV(c100;TB;W24H11)",
    "DoCoMo/2.0 SH902i (compatible; Y!J-SRD/1.0; http://help.yahoo.co.jp/help/jp/search/indexing/indexing-27.html)",
    "DoCoMo/2.0/SO502i (compatible; Y!J-SRD/1.0; http://help.yahoo.co.jp/help/jp/search/indexing/indexing-27.html)",
    "dodgebot/experimental",
    "Download-Tipp Linkcheck (http://download-tipp.de/)",
    "Drecombot/1.0 (http://career.drecom.jp/bot.html)",
    "dtSearchSpider",
    "DuckDuckBot/1.0; (+http://duckduckgo.com/duckduckbot.html)",
    "Dumbot(version 0.1 beta - dumbfind.com)",
    "Dumbot(version 0.1 beta - http://www.dumbfind.com/dumbot.html)",
    "Dumbot(version 0.1 beta)",
    "e-sense 1.0 ea(www.vigiltech.com/esensedisclaim.html)",
    "e-SocietyRobot(http://www.yama.info.waseda.ac.jp/~yamana/es/)",
    "eApolloBot/2.0 (compatible; heritrix/2.0.0-SNAPSHOT-20071024.170148 +http://www.eapollo-opto.com)",
    "EARTHCOM.info/1.x [www.earthcom.info]",
    "EARTHCOM.info/1.xbeta [www.earthcom.info]",
    "EasyDL/3.xx",
    "EasyDL/3.xx http://keywen.com/Encyclopedia/Bot",
    "EchO!/2.0",
    "egothor/3.0a (+http://www.xdefine.org/robot.html)",
    "EgotoBot/4.8 (+http://www.egoto.com/about.htm)",
    "ejupiter.com",
    "elfbot/1.0 (+http://www.uchoose.de/crawler/elfbot/)",
    "ELI/20070402:2.0 (DAUM RSS Robot, Daum Communications Corp.; +http://ws.daum.net/aboutkr.html)",
    "EMPAS_ROBOT",
    "EnaBot/1.x (http://www.enaball.com/crawler.html)",
    "Enfish Tracker",
    "Enterprise_Search/1.0",
    "Enterprise_Search/1.0.xxx",
    "Enterprise_Search/1.00.xxx;MSSQL (http://www.innerprise.net/es-spider.asp)",
    "envolk/1.7 (+http://www.envolk.com/envolkspiderinfo.php)",
    "envolk[ITS]spider/1.6(+http://www.envolk.com/envolkspider.html)",
    "EroCrawler",
    "ES.NET_Crawler/2.0 (http://search.innerprise.net/)",
    "eseek-larbin_2.6.2 (crawler@exactseek.com)",
    "ESISmartSpider",
    "eStyleSearch 4 (compatible; MSIE 6.0; Windows NT 5.0)",
    "EuripBot/0.x (+http://www.eurip.com) GetFile",
    "EuripBot/0.x (+http://www.eurip.com) GetRobots",
    "EuripBot/0.x (+http://www.eurip.com) PreCheck",
    "Eurobot/1.0 (http://www.ayell.eu)",
    "EvaalSE - bot@evaal.com",
    "eventax/1.3 (eventax; http://www.eventax.de/; info@eventax.de)",
    "Everest-Vulcan Inc./0.1 (R&D project; host=e-1-24; http://everest.vulcan.com/crawlerhelp)",
    "Everest-Vulcan Inc./0.1 (R&D project; http://everest.vulcan.com/crawlerhelp)",
    "Exabot-Images/1.0",
    "Exabot-Test/1.0",
    "Exabot/2.0",
    "Exabot/3.0",
    "ExactSeek Crawler/0.1",
    "exactseek-crawler-2.63 (crawler@exactseek.com)",
    "exactseek-pagereaper-2.63 (crawler@exactseek.com)",
    "exactseek.com",
    "Exalead NG/MimeLive Client (convert/http/0.120)",
    "Excalibur Internet Spider V6.5.4",
    "Execrawl/1.0 (Execrawl; http://www.execrawl.com/; bot@execrawl.com)",
    "exooba crawler/exooba crawler (crawler for exooba.com; http://www.exooba.com/; info at exooba dot com)",
    "exooba/exooba crawler (exooba; exooba)",
    "ExperimentalHenrytheMiragoRobot",
    "EyeCatcher (Download-tipp.de)/1.0",
    "Factbot 1.09 (see http://www.factbites.com/webmasters.php)",
    "factbot : http://www.factbites.com/robots",
    "Fast Crawler Gold Edition",
    "FAST Enterprise Crawler 6 (Experimental)",
    "FAST Enterprise Crawler 6 / Scirus scirus-crawler@fast.no; http://www.scirus.com/srsapp/contactus/",
    "FAST Enterprise Crawler 6 used by Cobra Development (admin@fastsearch.com)",
    "FAST Enterprise Crawler 6 used by Comperio AS (sts@comperio.no)",
    "FAST Enterprise Crawler 6 used by FAST (FAST)",
    "FAST Enterprise Crawler 6 used by Pages Jaunes (pvincent@pagesjaunes.fr)",
    "FAST Enterprise Crawler 6 used by Sensis.com.au Web Crawler (search_comments\at\sensis\dot\com\dot\au)",
    "FAST Enterprise Crawler 6 used by Singapore Press Holdings (crawler@sphsearch.sg)",
    "FAST Enterprise Crawler/6 (www.fastsearch.com)",
    "FAST Enterprise Crawler/6.4 (helpdesk at fast.no)",
    "FAST FirstPage retriever (compatible; MSIE 5.5; Mozilla/4.0)",
    "FAST MetaWeb Crawler (helpdesk at fastsearch dot com)",
    "Fast PartnerSite Crawler",
    "FAST-WebCrawler/2.2.10 (Multimedia Search) (crawler@fast.no; http://www.fast.no/faq/faqfastwebsearch/faqfastwebcrawler.html)",
    "FAST-WebCrawler/2.2.6 (crawler@fast.no; http://www.fast.no/faq/faqfastwebsearch/faqfastwebcrawler.html)",
    "FAST-WebCrawler/2.2.7 (crawler@fast.no; http://www.fast.no/faq/faqfastwebsearch/faqfastwebcrawler.html)http://www.fast.no",
    "FAST-WebCrawler/2.2.8 (crawler@fast.no; http://www.fast.no/faq/faqfastwebsearch/faqfastwebcrawler.html)http://www.fast.no",
    "FAST-WebCrawler/3.2 test",
    "FAST-WebCrawler/3.3 (crawler@fast.no; http://fast.no/support.php?c=faqs/crawler)",
    "FAST-WebCrawler/3.4/Nirvana (crawler@fast.no; http://fast.no/support.php?c=faqs/crawler)",
    "FAST-WebCrawler/3.4/PartnerSite (crawler@fast.no; http://fast.no/support.php?c=faqs/crawler)",
    "FAST-WebCrawler/3.5 (atw-crawler at fast dot no; http://fast.no/support.php?c=faqs/crawler)",
    "FAST-WebCrawler/3.6 (atw-crawler at fast dot no; http://fast.no/support/crawler.asp)",
    "FAST-WebCrawler/3.6/FirstPage (crawler@fast.no; http://fast.no/support.php?c=faqs/crawler)",
    "FAST-WebCrawler/3.7 (atw-crawler at fast dot no; http://fast.no/support/crawler.asp)",
    "FAST-WebCrawler/3.7/FirstPage (atw-crawler at fast dot no;http://fast.no/support/crawler.asp)",
    "FAST-WebCrawler/3.8 (atw-crawler at fast dot no; http://fast.no/support/crawler.asp)",
    "FAST-WebCrawler/3.8/Fresh (atw-crawler at fast dot no; http://fast.no/support/crawler.asp)",
    "FAST-WebCrawler/3.x Multimedia",
    "FAST-WebCrawler/3.x Multimedia (mm dash crawler at fast dot no)",
    "fastbot crawler beta 2.0 (+http://www.fastbot.de)",
    "FastBug http://www.ay-up.com",
    "FastCrawler 3.0.1 (crawler@1klik.dk)",
    "FastSearch Web Crawler for Verizon SuperPages (kevin.watters@fastsearch.com)",
    "Favcollector/2.0 (info@favcollector.com http://www.favcollector.com/)",
    "favo.eu crawler/0.6 (http://www.favo.eu)",
    "Faxobot/1.0",
    "Feed Seeker Bot (RSS Feed Seeker http://www.MyNewFavoriteThing.com/fsb.php)",
    "Feed24.com",
    "FeedChecker/0.01",
    "Feedfetcher-Google; (+http://www.google.com/feedfetcher.html)",
    "FeedHub FeedDiscovery/1.0 (http://www.feedhub.com)",
    "FeedHub MetaDataFetcher/1.0 (http://www.feedhub.com)",
    "Feedjit Favicon Crawler 1.0",
    "Felix - Mixcat Crawler (+http://mixcat.com)",
    "FFC Trap Door Spider",
    "Filtrbox/1.0",
    "Findexa Crawler (http://www.findexa.no/gulesider/article26548.ece)",
    "findlinks/x.xxx (+http://wortschatz.uni-leipzig.de/findlinks/)",
    "FineBot",
    "Firefly/1.0",
    "Firefly/1.0 (compatible; Mozilla 4.0; MSIE 5.5)",
    "Firefox (kastaneta03@hotmail.com)",
    "Firefox_1.0.6 (kasparek@naparek.cz)",
    "FirstGov.gov Search - POC:firstgov.webmasters@gsa.gov",
    "firstsbot",
    "Flapbot/0.7.2 (Flaptor Crawler; http://www.flaptor.com; crawler at flaptor period com)",
    "Flexum spider",
    "Flexum/2.0",
    "FlickBot 2.0 RPT-HTTPClient/0.3-3",
    "flunky",
    "FnooleBot/2.5.2 (+http://www.fnoole.com/addurl.html)",
    "FocusedSampler/1.0",
    "Folkd.com Spider/0.1 beta 1 (www.folkd.com)",
    "Fooky.com/ScorpionBot/ScoutOut; http://www.fooky.com/scorpionbots",
    "Francis/1.0 (francis@neomo.de http://www.neomo.de/)",
    "FreeFind.com-SiteSearchEngine/1.0 (http://freefind.com; spiderinfo@freefind.com)",
    "FreshNotes crawler< report problems to crawler-at-freshnotes-dot-com",
    "FTB-Bot http://www.findthebest.co.uk/",
    "FuseBulb.Com",
    "FyberSpider (+http://www.fybersearch.com/fyberspider.php)",
    "BeamMachine/0.5 (dead link remover of www.beammachine.net)",
    "CoBITSProbe",
    "Expired Domain Sleuth",
    "Filangy/0.01-beta (Filangy; http://www.nutch.org/docs/en/bot.html; filangy-agent@filangy.com)",
    "Filangy/1.0x (Filangy; http://www.filangy.com/filangyinfo.jsp?inc=robots.jsp; filangy-agent@filangy.com)",
    "Filangy/1.0x (Filangy; http://www.nutch.org/docs/en/bot.html; filangy-agent@filangy.com)",
    "fileboost.net/1.0 (+http://www.fileboost.net)",
    "FindAnISP.com_ISP_Finder_v99a",
    "collage.cgi/1.xx",
    "DTAAgent",
    "8484 Boston Project v 1.0",
    "Atomic_Email_Hunter/4.0",
    "atSpider/1.0",
    "autoemailspider",
    "bwh3_user_agent",
    "China Local Browse 2.6",
    "ContactBot/0.2",
    "ContentSmartz",
    "DataCha0s/2.0",
    "DataCha0s/2.0",
    "DBrowse 1.4b",
    "DBrowse 1.4d",
    "Demo Bot DOT 16b",
    "Demo Bot Z 16b",
    "DSurf15a 01",
    "DSurf15a 71",
    "DSurf15a 81",
    "DSurf15a VA",
    "EBrowse 1.4b",
    "Educate Search VxB",
    "EmailSiphon",
    "EmailSpider",
    "EmailWolf 1.00",
    "ESurf15a 15",
    "ExtractorPro",
    "Franklin Locator 1.8",
    "FSurf15a 01",
    "Full Web Bot 0416B",
    "Full Web Bot 0516B",
    "Full Web Bot 2816B",
    "AmiTCP Miami (AmigaOS 2.04)",
    "Anonymizer/1.1",
    "AnswerChase PROve x.0",
    "AnswerChase x.0",
    "AVSearch-2.0-fusionIdx-14-CompetitorWebSites",
    "bCentral Billing Post-Process",
    "BMCLIENT",
    "Bot mailto:craftbot@yahoo.com",
    "CamelHttpStream/1.0",
    "Cancer Information and Support International;",
    "CFNetwork/x.x",
    "CheckUrl",
    "Chilkat/1.0.0 (+http://www.chilkatsoft.com/ChilkatHttpUA.asp)",
    "CHttpClient by Open Text Corporation",
    "Contact",
    "Crawler",
    "Dart Communications PowerTCP",
    "dds explorer v1.0 beta",
    "DevComponents.com HtmlDocument Object",
    "Doubanbot/1.0 (bot@douban.com http://www.douban.com)",
    "Dr.Web (R) online scanner: http://online.drweb.com/",
    "fly/6.01 libwww/4.0D",
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
    "g2Crawler nobody@airmail.net",
    "Gaisbot/3.0+(robot06@gais.cs.ccu.edu.tw;+http://gais.cs.ccu.edu.tw/robot.php)",
    "Gaisbot/3.0+(robot05@gais.cs.ccu.edu.tw;+http://gais.cs.ccu.edu.tw/robot.php)",
    "Gaisbot/3.0 (jerry_wu@openfind.com.tw; http://gais.cs.ccu.edu.tw/robot.php)",
    "GalaxyBot/1.0 (http://www.galaxy.com/galaxybot.html)",
    "genieBot (http://64.5.245.11/faq/faq.html)",
    "genieBot ((http://64.5.245.11/faq/faq.html))",
    "Gigabot/3.0 (http://www.gigablast.com/spider.html)",
    "Gigabot/2.0/gigablast.com/spider.html",
    "Gigabot/2.0 (http://www.gigablast.com/spider.html)",
    "Gigabot/2.0",
    "Gigabot/1.0",
    "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322; Girafabot [girafa.com])",
    "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 4.0; Girafabot; girafabot at girafa dot com; http://www.girafa.com)",
    "Mozilla/4.0 (compatible; MSIE 5.0; Windows NT; Girafabot; girafabot at girafa dot com; http://www.girafa.com)",
    "Mozilla/4.0 (compatible; MSIE 5.0; Windows NT; Girafabot; girafabot at girafa dot com; http://www.girafa.com)",
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
    "Googlebot/2.1 (+http://www.googlebot.com/bot.html)",
    "Googlebot/2.1 (+http://www.google.com/bot.html)",
    "Googlebot-Image/1.0",
    "Gigabot/1.0",
    "Mozilla/5.0 GurujiBot/1.0 ( http://www.guruji.com/en/WebmasterFAQ.html)",
    "Mozilla/5.0 (compatible; GurujiBot/1.0; +http://www.guruji.com/en/WebmasterFAQ.html)",
    "GurujiBot/1.0 (+http://www.guruji.com/WebmasterFAQ.html)",
    "GurujiBot/1.0 (+http://www.guruji.com/en/WebmasterFAQ.html)",
    "HappyFunBot/1.1 ( http://www.happyfunsearch.com/bot.html)",
    "hl_ftien_spider_v1.1",
    "hl_ftien_spider",
    "holmes/3.9 (someurl.co.cc)",
    "holmes/3.12.4 (http://morfeo.centrum.cz/bot)",
    "holmes/3.12.3 (http://morfeo.centrum.cz/bot)",
    "holmes/3.12.2 (http://morfeo.centrum.cz/bot)",
    "holmes/3.12.1 (http://morfeo.centrum.cz/bot)",
    "htdig/3.1.6 (unconfigured@htdig.searchengine.maintainer)",
    "htdig/3.1.6 (mathieu.peltier@inrialpes.fr)",
    "htdig/3.1.5 (webmaster@online-medien.de)",
    "htdig/3.1.5 (root@localhost)",
    "htdig/3.1.5 (infosys@storm.rmi.org)",
    "htdig/3.1.5",
    "iaskspider/2.0(+http://iask.com/help/help_index.html)",
    "iaskspider",
    "ia_archiver/8.9 (Windows NT 3.1; en-US;)",
    "ia_archiver/8.9 (Windows 3.9; en-US;)",
    "ia_archiver/8.9 (Linux 1.0; en-US;)",
    "ia_archiver/8.8 (Windows XP 7.2; en-US;)",
    "ia_archiver/8.8 (Windows XP 3.0; en-US;)",
    "ia_archiver/8.2 (Windows 7.6; en-US;)",
    "ia_archiver/8.1 (Windows 2000 1.9; en-US;)",
    "ia_archiver/8.0 (Windows 2.4; en-US;)",
    "ia_archiver",
    "iCCrawler (http://www.iccenter.net/bot.htm)",
    "ichiro/4.0 (http://help.goo.ne.jp/door/crawler.html)",
    "ichiro/3.0 (http://help.goo.ne.jp/door/crawler.html)",
    "ichiro/2.0+(http://help.goo.ne.jp/door/crawler.html)",
    "ichiro/2.0 (ichiro@nttr.co.jp)",
    "ichiro/2.0 (http://help.goo.ne.jp/door/crawler.html)",
    "igdeSpyder (compatible; igde.ru; +http://igde.ru/doc/tech.html)",
    "IRLbot/3.0 (compatible; MSIE 6.0; http://irl.cs.tamu.edu/crawler/)",
    "IRLbot/3.0 (compatible; MSIE 6.0; http://irl.cs.tamu.edu/crawler)",
    "IRLbot/2.0 (compatible; MSIE 6.0; http://irl.cs.tamu.edu/crawler)",
    "IRLbot/2.0 (+http://irl.cs.tamu.edu/crawler)",
    "IRLbot/2.0 ( http://irl.cs.tamu.edu/crawler)",
    "IssueCrawler",
    "Jaxified Bot (+http://www.jaxified.com/crawler/)",
    "Jyxobot/1",
    "Mozilla/5.0 (compatible; KoepaBot BETA; http://www.koepa.nl/bot.html)",
    "L.webis/0.87 (http://webalgo.iit.cnr.it/index.php?pg=lwebis)",
    "Mozilla/5.0 larbin@unspecified.mail",
    "larbin_2.6.3 zumesun@hotmail.com",
    "larbin_2.6.3 tangyi858@163.com",
    "larbin_2.6.3 ltaa_web_crawler@groupes.epfl.ch",
    "larbin_2.6.3 larbin2.6.3@unspecified.mail",
    "larbin_2.6.3 gqnmgsp@ruc.edu.cn",
    "larbin_2.6.3 ghary@sohu.com",
    "larbin_2.6.3 capveg@cs.umd.edu",
    "larbin_2.6.3 (wgao@genieknows.com)",
    "larbin_2.6.3 (ltaa_web_crawler@groupes.epfl.ch)",
    "larbin_2.6.3 (larbin@behner.org)",
    "larbin_2.6.3 (larbin2.6.3@unspecified.mail)",
    "larbin_2.6.2 vitalbox1@hotmail.com",
    "larbin_2.6.2 pierre@micro-fun.ch",
    "larbin_2.6.2 listonATccDOTgatechDOTedu",
    "larbin_2.6.2 larbin@correa.org",
    "larbin_2.6.2 larbin2.6.2@unspecified.mail",
    "larbin_2.6.2 kalou@kalou.net",
    "larbin_2.6.2 dthunen@princeton.edu",
    "larbin_2.6.2 (vitalbox1@hotmail.com)",
    "larbin_2.6.2 (pierre@micro-fun.ch)",
    "larbin_2.6.2 (larbin@correa.org)",
    "larbin_2.6.2 (larbin2.6.2@unspecified.mail)",
    "larbin_2.6.1 larbin2.6.1@unspecified.mail",
    "larbin_2.5.0 (larbin2.5.0@unspecified.mail)",
    "larbin_xy250 larbin2.6.3@unspecified.mail",
    "larbin_test nobody@airmail.etn",
    "larbin_test (nobody@airmail.etn)",
    "LARBIN-EXPERIMENTAL efp@gmx.net",
    "ldspider (http://code.google.com/p/ldspider/wiki/Robots)",
    "LexxeBot/1.0 (lexxebot@lexxe.com)",
    "Linguee Bot (http://www.linguee.com/bot; bot@linguee.com)",
    "LinkWalker/2.0",
    "LinkWalker",
    "lmspider lmspider@scansoft.com",
    "lmspider (lmspider@scansoft.com)",
    "lwp-trivial/1.41",
    "lwp-trivial/1.38",
    "lwp-trivial/1.36",
    "lwp-trivial/1.35",
    "lwp-trivial/1.33",
    "http://www.mabontland.com",
    "magpie-crawler/1.1 (U; Linux amd64; en-GB; +http://www.brandwatch.net)",
    "Mediapartners-Google/2.1",
    "Mozilla/5.0 (compatible; MJ12bot/v1.2.4; http://www.majestic12.co.uk/bot.php?+)",
    "Mozilla/5.0 (compatible; MJ12bot/v1.2.3; http://www.majestic12.co.uk/bot.php?+)",
    "MJ12bot/v1.0.8 (http://majestic12.co.uk/bot.php?+)",
    "MJ12bot/v1.0.7 (http://majestic12.co.uk/bot.php?+)",
    "MJ12bot/v1.0.6 (http://majestic12.co.uk/bot.php?+)",
    "MJ12bot/v1.0.5 (http://majestic12.co.uk/bot.php?+)",
    "Mnogosearch-3.1.21",
    "mogimogi/1.0",
    "Mozilla/5.0 (compatible; MojeekBot/2.0; http://www.mojeek.com/bot.html)",
    "MojeekBot/0.2 (archi; http://www.mojeek.com/bot.html)",
    "Moreoverbot/5.1 ( http://w.moreover.com; webmaster@moreover.com) Mozilla/5.0",
    "Moreoverbot/5.00 (+http://www.moreover.com; webmaster@moreover.com)",
    "Moreoverbot/5.00 (+http://www.moreover.com)",
    "Morning Paper 1.0 (robots.txt compliant!)",
    "msnbot/2.1",
    "msnbot/2.0b",
    "msnbot/1.1 (+http://search.msn.com/msnbot.htm)",
    "msnbot/1.1",
    "msnbot/1.0 (+http://search.msn.com/msnbot.htm)",
    "msnbot/0.9 (+http://search.msn.com/msnbot.htm)",
    "msnbot/0.11 ( http://search.msn.com/msnbot.htm)",
    "MSNBOT/0.1 (http://search.msn.com/msnbot.htm)",
    "MSRBOT (http://research.microsoft.com/research/sv/msrbot/)",
    "MSRBOT",
    "MVAClient",
    "Mozilla/5.0 (compatible; mxbot/1.0; +http://www.chainn.com/mxbot.html)",
    "Mozilla/5.0 (compatible; mxbot/1.0; http://www.chainn.com/mxbot.html)",
    "NetResearchServer/4.0(loopimprovements.com/robot.html)",
    "NetResearchServer/3.5(loopimprovements.com/robot.html)",
    "NetResearchServer/2.8(loopimprovements.com/robot.html)",
    "NetResearchServer/2.7(loopimprovements.com/robot.html)",
    "NetResearchServer/2.5(loopimprovements.com/robot.html)",
    "NetResearchServer(http://www.look.com)",
    "Mozilla/5.0 (compatible; NetSeer crawler/2.0; +http://www.netseer.com/crawler.html; crawler@netseer.com)",
    "NewsGator/2.5 (http://www.newsgator.com; Microsoft Windows NT 5.1.2600.0; .NET CLR 1.1.4322.2032)",
    "NewsGator/2.0 Bot (http://www.newsgator.com)",
    "NG-Search/0.9.8 (http://www.ng-search.com)",
    "NG-Search/0.86 (+http://www.ng-search.com)",
    "NG-Search/0.86 ( http://www.ng-search.com)",
    "nicebot",
    "noxtrumbot/1.0 (crawler@noxtrum.com)",
    "Nusearch Spider (www.nusearch.com)",
    "nuSearch Spider (compatible; MSIE 4.01; Windows NT)",
    "NutchCVS/0.8-dev (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
    "NutchCVS/0.7.2 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
    "NutchCVS/0.7.1 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
    "NutchCVS/0.7.1 (Nutch running at UW; http://crawlers.cs.washington.edu/; sycrawl@cs.washington.edu)",
    "NutchCVS/0.7 (Nutch; http://lucene.apache.org/nutch/bot.html; nutch-agent@lucene.apache.org)",
    "NutchCVS/0.06-dev (Nutch; http://www.nutch.org/docs/en/bot.html; nutch-agent@lists.sourceforge.net)",
    "NutchCVS/0.06-dev (Nutch; http://www.nutch.org/docs/en/bot.html; jagdeepssandhu@hotmail.com)",
    "NutchCVS/0.05 (Nutch; http://www.nutch.org/docs/en/bot.html; nutch-agent@lists.sourceforge.net)",
    "Nymesis/1.0 (http://nymesis.com)",
    "oegp v. 1.3.0",
    "omgilibot/0.4 +http://omgili.com",
    "omgilibot/0.3 +http://www.omgili.com/Crawler.html",
    "omgilibot/0.3 http://www.omgili.com/Crawler.html",
    "OmniExplorer_Bot/6.70 (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/6.65a (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/6.63b (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/6.62 (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/6.60 (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/6.47 (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/5.91c (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/5.28 (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/5.25 (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/5.20 (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/5.01 (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/4.80 (+http://www.omni-explorer.com) WorldIndexer",
    "OmniExplorer_Bot/4.32 (+http://www.omni-explorer.com) WorldIndexer",
    "OOZBOT/0.20 ( -- ; http://www.setooz.com/oozbot.html ; agentname at setooz dot_com )",
    "OOZBOT/0.17 (--; http://www.setooz.com/oozbot.html; pvvpr at iiit dot ac dot in)",
    "Orbiter (+http://www.dailyorbit.com/bot.htm)",
    "PageBitesHyperBot/600 (http://www.pagebites.com/)",
    "Mozilla/5.0 (compatible; Peew/1.0; http://www.peew.de/crawler/)",
    "polybot 1.0 (http://cis.poly.edu/polybot/)",
    "Pompos/1.3 http://dir.com/pompos.html",
    "Pompos/1.2 http://pompos.iliad.fr",
    "Pompos/1.1 http://pompos.iliad.fr",
    "PostPost/1.0 (+http://postpo.st/crawlers)",
    "psbot/0.1 (+http://www.picsearch.com/bot.html)",
    "PycURL/7.23.1",
    "PycURL/7.19.7",
    "PycURL/7.19.5",
    "PycURL/7.19.3",
    "PycURL/7.19.0",
    "PycURL/7.18.2",
    "PycURL/7.18.0",
    "PycURL/7.16.4",
    "PycURL/7.15.5",
    "PycURL/7.13.2",
    "PycURL",
    "Qseero v1.0.0",
    "radian6_default_(www.radian6.com/crawler)",
    "RAMPyBot - www.giveRAMP.com/0.1 (RAMPyBot - www.giveRAMP.com; http://www.giveramp.com/bot.html; support@giveRAMP.com)",
    "RufusBot (Rufus Web Miner; http://64.124.122.252/feedback.html)",
    "SandCrawler - Compatibility Testing",
    "SBIder/0.8-dev (SBIder; http://www.sitesell.com/sbider.html; http://support.sitesell.com/contact-support.html)",
    "Mozilla/5.0 (compatible; ScoutJet; http://www.scoutjet.com/)",
    "Scrubby/2.2 (http://www.scrubtheweb.com/)",
    "Mozilla/5.0 (compatible; Scrubby/2.2; +http://www.scrubtheweb.com/)",
    "Mozilla/5.0 (compatible; Scrubby/2.2; http://www.scrubtheweb.com/)",
    "Scrubby/2.1 (http://www.scrubtheweb.com/)",
    "Mozilla/5.0 (compatible; Scrubby/2.1; +http://www.scrubtheweb.com/abs/meta-check.html)",
    "SearchSight/2.0 (http://SearchSight.com/)",
    "Seekbot/1.0 (http://www.seekbot.net/bot.html) RobotsTxtFetcher/1.2",
    "Seekbot/1.0 (http://www.seekbot.net/bot.html) HTTPFetcher/2.1",
    "Seekbot/1.0 (http://www.seekbot.net/bot.html) HTTPFetcher/0.3",
    "Seekbot/1.0 (http://www.seekbot.net/bot.html)",
    "semanticdiscovery/0.1",
    "Sensis Web Crawler (search_comments\at\sensis\dot\com\dot\au)",
    "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0) SEOChat::Bot v1.1",
    "SeznamBot/2.0 (+http://fulltext.seznam.cz/)",
    "SeznamBot/2.0 (+http://fulltext.sblog.cz/robot/)",
    "Shim-Crawler(Mozilla-compatible; http://www.logos.ic.i.u-tokyo.ac.jp/crawler/; crawl@logos.ic.i.u-tokyo.ac.jp)",
    "Shim-Crawler",
    "Mozilla/4.0 (compatible: Shoula robot)",
    "silk/1.0 (+http://www.slider.com/silk.htm)/3.7",
    "Silk/1.0",
    "Mozilla/5.0 (compatible; SiteBot/0.1; +http://www.sitebot.org/robot/)",
    "Mozilla/5.0 (compatible; SiteBot/0.1; http://www.sitebot.org/robot/)",
    "Snappy/1.1 ( http://www.urltrends.com/ )",
    "sogou spider",
    "Sosospider+(+http://help.soso.com/webspider.htm)",
    "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) Speedy Spider (http://www.entireweb.com/about/search_tech/speedy_spider/)",
    "Mozilla/5.0 (compatible; Speedy Spider; http://www.entireweb.com/about/search_tech/speedy_spider/)",
    "Speedy Spider (Entireweb; Beta/1.3; http://www.entireweb.com/about/search_tech/speedyspider/)",
    "Speedy Spider (Entireweb; Beta/1.2; http://www.entireweb.com/about/search_tech/speedyspider/)",
    "Speedy Spider (Entireweb; Beta/1.1; http://www.entireweb.com/about/search_tech/speedyspider/)",
    "Speedy Spider (Entireweb; Beta/1.0; http://www.entireweb.com/about/search_tech/speedyspider/)",
    "Speedy Spider (Beta/1.0; www.entireweb.com)",
    "Speedy Spider (http://www.entireweb.com/about/search_tech/speedy_spider/)",
    "Speedy Spider (http://www.entireweb.com/about/search_tech/speedyspider/)",
    "Speedy Spider (http://www.entireweb.com)",
    "Sqworm/2.9.85-BETA (beta_release; 20011115-775; i686-pc-linux-gnu)",
    "StackRambler/2.0 (MSIE incompatible)",
    "StackRambler/2.0",
    "Mozilla/5.0 (compatible; suggybot v0.01a, http://blog.suggy.com/was-ist-suggy/suggy-webcrawler/)",
    "SurveyBot/2.3+(Whois+Source)",
    "SurveyBot/2.3 (Whois Source)",
    "SynooBot/0.7.1 (SynooBot; http://www.synoo.de/bot.html; webmaster@synoo.com)",
    "Mozilla/2.0 (compatible; Ask Jeeves/Teoma; +http://sp.ask.com/docs/about/tech_crawling.html)",
    "Mozilla/2.0 (compatible; Ask Jeeves/Teoma; +http://about.ask.com/en/docs/about/webmasters.shtml)",
    "Mozilla/2.0 (compatible; Ask Jeeves/Teoma)",
    "TerrawizBot/1.0 (+http://www.terrawiz.com/bot.html)",
    "TheSuBot/0.2 (www.thesubot.de)",
    "TheSuBot/0.1 (www.thesubot.de)",
    "Thumbnail.CZ robot 1.1 (http://thumbnail.cz/why-no-robots-txt.html)",
    "TinEye/1.1 (http://tineye.com/crawler.html)",
    "TinEye",
    "truwoGPS/1.0 (GNU/Linux; U; i686; en-US; +http://www.lan4lano.net/browser.html )",
    "TurnitinBot/2.1 (http://www.turnitin.com/robot/crawlerinfo.html)",
    "TurnitinBot/2.0 http://www.turnitin.com/robot/crawlerinfo.html",
    "TurnitinBot/1.5 http://www.turnitin.com/robot/crawlerinfo.html",
    "TurnitinBot/1.5 (http://www.turnitin.com/robot/crawlerinfo.html)",
    "TurnitinBot/1.5 http://www.turnitin.com/robot/crawlerinfo.html",
    "TurnitinBot/1.5 (http://www.turnitin.com/robot/crawlerinfo.html)",
    "Mozilla/5.0 (compatible; TweetedTimes Bot/1.0; http://tweetedtimes.com)",
    "TwengaBot",
    "updated/0.1-beta (updated; http://www.updated.com; updated@updated.com)",
    "Mozilla/5.0 (compatible; Urlfilebot/2.2; +http://urlfile.com/bot.html)",
    "Mozilla/4.0 (compatible; Vagabondo/4.0Beta; webcrawler at wise-guys dot nl; http://webagent.wise-guys.nl/; http://www.wise-guys.nl/)",
    "Mozilla/4.0 (compatible; Vagabondo/2.2; webcrawler at wise-guys dot nl; http://webagent.wise-guys.nl/)",
    "Mozilla/5.0 (compatible; Vagabondo/2.1; webcrawler at wise-guys dot nl; http://webagent.wise-guys.nl/)",
    "Mozilla/3.0 (Vagabondo/2.0 MT; webcrawler@NOSPAMexperimental.net; http://aanmelden.ilse.nl/?aanmeld_mode=webhints)",
    "Mozilla/4.0 (compatible; MSIE 5.0; Windows 95) VoilaBot BETA 1.2 (http://www.voila.com/)",
    "Vortex/2.2 (+http://marty.anstey.ca/robots/vortex/)",
    "Vortex/2.2 ( http://marty.anstey.ca/robots/vortex/)",
    "voyager/1.0",
    "voyager/2.0 (http://www.kosmix.com/crawler.html)",
    "VYU2 (GNU; OpenRISC)",
    "webcollage/1.93",
    "webcollage/1.129",
    "webcollage/1.125",
    "webcollage/1.117",
    "webcollage/1.114",
    "Websquash.com (Add url robot)",
    "http://www.almaden.ibm.com/cs/crawler [wf84]",
    "WoFindeIch Robot 1.0(+http://www.search.wofindeich.com/robot.php)",
    "WoFindeIch Robot 1.0( http://www.search.wofindeich.com/robot.php)",
    "WomlpeFactory/0.1 (+http://www.Womple.com/bot.html)",
    "Xaldon_WebSpider/2.0.b1",
    "Xaldon_WebSpider/2.0.b1",
    "yacybot (x86 Windows XP 5.1; java 1.6.0_12; Europe/de) http://yacy.net/bot.html",
    "yacybot (x86 Windows XP 5.1; java 1.6.0_11; Europe/de) http://yacy.net/bot.html",
    "yacybot (x86 Windows XP 5.1; java 1.6.0; Europe/de) http://yacy.net/yacy/bot.html",
    "yacybot (x86 Windows 2000 5.0; java 1.6.0_16; Europe/de) http://yacy.net/bot.html",
    "yacybot (ppc Mac OS X 10.5.2; java 1.5.0_13; Europe/de) http://yacy.net/bot.html",
    "yacybot (ppc Mac OS X 10.4.10; java 1.5.0_07; Europe/de) http://yacy.net/bot.html",
    "yacybot (i386 Mac OS X 10.5.7; java 1.5.0_16; Europe/de) http://yacy.net/bot.html",
    "yacybot (i386 Linux 2.6.9-023stab046.2-smp; java 1.6.0_05; Europe/en) http://yacy.net/bot.html",
    "yacybot (i386 Linux 2.6.8-022stab070.5-enterprise; java 1.4.2-03; Europe/en) yacy.net",
    "yacybot (i386 Linux 2.6.31-16-generic; java 1.6.0_15; Europe/en) http://yacy.net/bot.html",
    "yacybot (i386 Linux 2.6.26-2-686; java 1.6.0_0; Europe/en) http://yacy.net/bot.html",
    "yacybot (i386 Linux 2.6.24-28-generic; java 1.6.0_20; Europe/en) http://yacy.net/bot.html",
    "yacybot (i386 Linux 2.6.24-24-generic; java 1.6.0_07; Europe/en) http://yacy.net/bot.html",
    "yacybot (i386 Linux 2.6.24-23-generic; java 1.6.0_16; Europe/en) http://yacy.net/bot.html",
    "yacybot (i386 Linux 2.6.23; java 1.6.0_17; Europe/en) http://yacy.net/bot.html",
    "yacybot (i386 Linux 2.6.23; java 1.6.0_04; Europe/en) http://yacy.net/bot.html",
    "yacybot (i386 Linux 2.6.22-14-generic; java 1.6.0_03; Europe/de) http://yacy.net/bot.html",
    "yacybot (amd64 Windows 7 6.1; java 1.6.0_17; Europe/de) http://yacy.net/bot.html",
    "yacybot (amd64 Linux 2.6.28-18-generic; java 1.6.0_0; Europe/en) http://yacy.net/bot.html",
    "yacybot (amd64 Linux 2.6.16-2-amd64-k8-smp; java 1.5.0_10; Europe/en) http://yacy.net/yacy/bot.html",
    "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)",
    "Mozilla/5.0 (compatible; Yahoo! Slurp China; http://misc.yahoo.com.cn/help.html)",
    "YahooSeeker/1.2 (compatible; Mozilla 4.0; MSIE 5.5; yahooseeker at yahoo-inc dot com ; http://help.yahoo.com/help/us/shop/merchant/)",
    "YahooSeeker-Testing/v3.9 (compatible; Mozilla 4.0; MSIE 5.5; http://search.yahoo.com/)",
    "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)",
    "Mozilla/5.0 (compatible; YandexImages/3.0; +http://yandex.com/bots)",
    "Yasaklibot/v1.2 (http://www.Yasakli.com/bot.php)",
    "Yeti/1.0 (NHN Corp.; http://help.naver.com/robots/)",
    "Yeti/1.0 (+http://help.naver.com/robots/)",
    "Mozilla/5.0 (compatible; YodaoBot/1.0; http://www.yodao.com/help/webmaster/spider/; )",
    "yoogliFetchAgent/0.1",
    "Mozilla/5.0 (compatible; YoudaoBot/1.0; http://www.youdao.com/help/webmaster/spider/; )",
    "Zao/0.1 (http://www.kototoi.org/zao/)",
    "Zao/0.1 (http://www.kototoi.org/zao/)",
    "Mozilla/4.0 (compatible; Zealbot 1.0)",
    "zspider/0.9-dev http://feedback.redkolibri.com/",
    "Mozilla/4.0 compatible ZyBorg/1.0 DLC (wn.zyborg@looksmart.net; http://www.WISEnutbot.com)",
    "Mozilla/4.0 compatible ZyBorg/1.0 Dead Link Checker (wn.zyborg@looksmart.net; http://www.WISEnutbot.com)",
    "Mozilla/4.0 compatible ZyBorg/1.0 Dead Link Checker (wn.dlc@looksmart.net; http://www.WISEnutbot.com)",
    "Mozilla/4.0 compatible ZyBorg/1.0 (wn.zyborg@looksmart.net; http://www.WISEnutbot.com)",
    "Mozilla/4.0 compatible ZyBorg/1.0 (wn-16.zyborg@looksmart.net; http://www.WISEnutbot.com)",
    "Mozilla/4.0 compatible ZyBorg/1.0 (wn-14.zyborg@looksmart.net; http://www.WISEnutbot.com)",
  ]

  # default key length: 5 characters
  mattr_accessor :unique_key_length
  self.unique_key_length = 5

  # character set to chose from:
  #  :alphanum     - a-z0-9     -  has about 60 million possible combos
  #  :alphanumcase - a-zA-Z0-9  -  has about 900 million possible combos
  mattr_accessor :charset
  self.charset = :alphanum

  #The default redirection url when the key isn't found
  mattr_accessor :default_redirect
  self.default_redirect = '/'

  # forbidden keys
  mattr_accessor :forbidden_keys
  self.forbidden_keys = []

  def self.key_chars
    CHARSETS[charset]
  end
end

# Require our railtie and engine
require "shortener/railtie"
require "shortener/engine"
